//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEntySubType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountEntySubType()
        {
            this.AccountEntryDetails = new HashSet<AccountEntryDetail>();
        }
    
        public int AccountEntySubTypeId { get; set; }
        public short AccountEntryTypeId { get; set; }
        public string AccountEntySubTypeName { get; set; }
        public string AccountEntySubTypeSummary { get; set; }
        public string AccountEntySubTypeDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountEntryDetail> AccountEntryDetails { get; set; }
        public virtual AccountEntryType AccountEntryType { get; set; }
    }
}
