//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEntryDetailBreakdown
    {
        public long AccountEntryDetailBreakDownId { get; set; }
        public long AccountEntryDetailId { get; set; }
        public string BreakdownTitle { get; set; }
        public string BreakdownText { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    
        public virtual AccountEntryDetail AccountEntryDetail { get; set; }
    }
}
