//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEntryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountEntryDetail()
        {
            this.AccountEntryDetailBreakdowns = new HashSet<AccountEntryDetailBreakdown>();
        }
    
        public long AccountEntryDetailId { get; set; }
        public long AccountEntryHeaderId { get; set; }
        public Nullable<int> AccountEntrySubTypeId { get; set; }
        public string DetailTitle { get; set; }
        public string DetailText { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AccountEntryHeader AccountEntryHeader { get; set; }
        public virtual AccountEntySubType AccountEntySubType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountEntryDetailBreakdown> AccountEntryDetailBreakdowns { get; set; }
    }
}
