//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColleaguePayData
    {
        public int PersonNumber { get; set; }
        public int WeekNumber { get; set; }
        public decimal WorkedHours { get; set; }
        public decimal Holiday { get; set; }
        public decimal Sickness { get; set; }
        public decimal PaidAbsence { get; set; }
        public decimal UnpaidAbsence { get; set; }
    }
}
