//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentDetail
    {
        public int ContentDetailId { get; set; }
        public Nullable<int> ContentHeaderId { get; set; }
        public string ContentDetailTitle { get; set; }
        public string ContentDetailSummary { get; set; }
        public string ContentDetailText { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ContentHeader ContentHeader { get; set; }
    }
}
