//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCW_Managers
    {
        public string Store_num { get; set; }
        public string Emp_num { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Role { get; set; }
        public string DOJ { get; set; }
        public string DOL { get; set; }
        public string Date_in_Current_Role { get; set; }
        public string Date_in_Current_Department { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    }
}
