//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyFootfall
    {
        public int DailyFootfallId { get; set; }
        public Nullable<int> Branch { get; set; }
        public string ProfileType { get; set; }
        public string Day { get; set; }
        public Nullable<double> C0700 { get; set; }
        public Nullable<double> C0800 { get; set; }
        public Nullable<double> C0900 { get; set; }
        public Nullable<double> C1000 { get; set; }
        public Nullable<double> C1100 { get; set; }
        public Nullable<double> C1200 { get; set; }
        public Nullable<double> C1300 { get; set; }
        public Nullable<double> C1400 { get; set; }
        public Nullable<double> C1500 { get; set; }
        public Nullable<double> C1600 { get; set; }
        public Nullable<double> C1700 { get; set; }
        public Nullable<double> C1800 { get; set; }
        public Nullable<double> C1900 { get; set; }
        public Nullable<double> C2000 { get; set; }
        public Nullable<double> C2100 { get; set; }
        public Nullable<double> C2200 { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public string InvoiceGroupYearName { get; set; }
    }
}
