//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardData
    {
        public int DashBoardDataId { get; set; }
        public string Year { get; set; }
        public Nullable<byte> Quarter { get; set; }
        public Nullable<byte> Period { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<short> BranchNumber { get; set; }
        public string UkBranchNumber { get; set; }
        public string StoreName { get; set; }
        public string Division { get; set; }
        public Nullable<short> Region { get; set; }
        public string RegionName { get; set; }
        public Nullable<short> TotalHeadCount { get; set; }
        public Nullable<short> TimeCardsCompleted { get; set; }
        public Nullable<short> ZeroHour { get; set; }
        public Nullable<double> ContractHours { get; set; }
        public Nullable<double> FTContractHours { get; set; }
        public Nullable<double> PTContractHours { get; set; }
        public Nullable<double> OriginalTarget { get; set; }
        public Nullable<double> FinalTarget { get; set; }
        public Nullable<double> HolidayTaken { get; set; }
        public Nullable<double> LTS { get; set; }
        public Nullable<double> FTLeakage { get; set; }
        public Nullable<short> LeakageCount { get; set; }
        public Nullable<double> AllApprovedHours { get; set; }
        public Nullable<double> PayrollCorrections { get; set; }
        public Nullable<double> SOH { get; set; }
        public Nullable<bool> OverTargetFlag { get; set; }
        public Nullable<bool> OverContractFlag { get; set; }
        public Nullable<short> ComplianceScore { get; set; }
        public Nullable<short> SOHUtilization { get; set; }
        public Nullable<bool> UtilizationZeroFlag { get; set; }
        public Nullable<double> GSContract { get; set; }
        public Nullable<double> GSTarget { get; set; }
        public Nullable<double> GSHolidayTaken { get; set; }
        public Nullable<double> GSFTLeakage { get; set; }
        public Nullable<double> GSAllApprovedHours { get; set; }
        public Nullable<double> GSSOHSpend { get; set; }
        public Nullable<bool> GSOverTargetFlag { get; set; }
        public Nullable<bool> GSOverContractFlag { get; set; }
        public string StoreFlag { get; set; }
        public Nullable<short> StoreCount { get; set; }
        public Nullable<short> FTHeadcountSAS { get; set; }
        public Nullable<short> FTHeadcountSIS { get; set; }
        public Nullable<double> ContractBaseTarget { get; set; }
        public Nullable<bool> PaidForHoursNotWorkedCompliance { get; set; }
        public Nullable<double> SATSOH { get; set; }
        public Nullable<double> SATTarget { get; set; }
        public Nullable<double> ServiceLV1SOH { get; set; }
        public Nullable<double> ServiceLV1Target { get; set; }
        public Nullable<double> ServiceLV2SOH { get; set; }
        public Nullable<double> ServiceLV2Target { get; set; }
        public Nullable<double> SATContractHours { get; set; }
        public Nullable<double> ServiceLV1ContractHours { get; set; }
        public Nullable<double> ServiceLV2ContractHours { get; set; }
        public Nullable<bool> C25PercOver { get; set; }
        public Nullable<bool> C25PercUnder { get; set; }
        public Nullable<bool> PlusMinus10Perc { get; set; }
        public Nullable<double> Awol { get; set; }
        public Nullable<double> Suspension { get; set; }
        public Nullable<double> Sickness { get; set; }
        public Nullable<double> GSTraining { get; set; }
        public Nullable<double> SATTraining { get; set; }
        public Nullable<double> L1Training { get; set; }
        public Nullable<double> L2Training { get; set; }
        public Nullable<double> SATHoliday { get; set; }
        public Nullable<double> L1Holiday { get; set; }
        public Nullable<double> L2Holiday { get; set; }
    }
}
