//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DxCpIEReportingModel : DbContext
    {
        public DxCpIEReportingModel()
            : base("name=DxCpIEReportingModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleReference> RoleReferences { get; set; }
        public virtual DbSet<StoreReference> StoreReferences { get; set; }
    
        [DbFunction("DxCpIEReportingModel", "fn_UnmatchedRoles")]
        public virtual IQueryable<string> fn_UnmatchedRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[DxCpIEReportingModel].[fn_UnmatchedRoles]()");
        }
    
        [DbFunction("DxCpIEReportingModel", "fn_UnmatchedStores")]
        public virtual IQueryable<string> fn_UnmatchedStores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[DxCpIEReportingModel].[fn_UnmatchedStores]()");
        }
    }
}
