//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class footfall_raw
    {
        public string Key { get; set; }
        public string Invoice_Group_Year_Name { get; set; }
        public Nullable<short> Invoice_Group_Week_Number { get; set; }
        public string Invoice_Day_Name { get; set; }
        public Nullable<short> Branch_Number { get; set; }
        public Nullable<short> Hour_In_Day_24 { get; set; }
        public Nullable<short> Footfall_Volume { get; set; }
    }
}
