//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayPlanningStore
    {
        public int EntryId { get; set; }
        public int WeekNumber { get; set; }
        public string BranchNumber { get; set; }
        public Nullable<int> Taken { get; set; }
        public Nullable<int> Scheduled { get; set; }
        public Nullable<int> Guideline { get; set; }
    }
}
