//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncorrectBranchLog
    {
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<short> OriginalBranch { get; set; }
        public short ChangeToBranch { get; set; }
        public string IpSource { get; set; }
        public string ReasonForChange { get; set; }
        public Nullable<bool> Reviewed { get; set; }
    }
}
