//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteFeedback
    {
        public int EntryId { get; set; }
        public short StoreNumber { get; set; }
        public string FeedbackText { get; set; }
        public System.DateTime DateTimeSubmitted { get; set; }
    }
}
