//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.WorkforceManagement.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyFootfall
    {
        public int WeeklyFootfallId { get; set; }
        public Nullable<int> Branch { get; set; }
        public string ProfileType { get; set; }
        public Nullable<double> Sunday { get; set; }
        public Nullable<double> Monday { get; set; }
        public Nullable<double> Tuesday { get; set; }
        public Nullable<double> Wednesday { get; set; }
        public Nullable<double> Thursday { get; set; }
        public Nullable<double> Friday { get; set; }
        public Nullable<double> Saturday { get; set; }
        public string InvoiceGroupYearName { get; set; }
        public Nullable<int> InvoiceGroupWeekNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
